// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "SpaceXNetwork",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "SpaceXNetwork",
            targets: ["AppModule"],
            bundleIdentifier: "com.Tudor.SpaceXNetwork",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .bicycle),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/b5i/YouTubeKit", .branch("main"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "YouTubeKit", package: "youtubekit")
            ],
            path: "."
        )
    ]
)